### ISSUE TITLE
how to add the side scroll bar?

### ISSUE THREAD

**Issue by anthrolisp** [abrahambahez/Brutalism#1]
i absolutely love this theme, but am missing the side scroll bar on longer pages. is there any css snippet i could add to keep the theme and the sidebar together? thank you in advance!

**Comment by abrahambahez** [comment]
Hey! I'm glad you like the theme. I've just update it to bring back the scrollbar to the main theme. I was adding some hide-UI css in another snippet anyway, so I decided to put that in a separate css file and offer it as an independent complement snippet. If you update the theme the scrollbar should return. Cheers!
